### ISSUE TITLE
"No Refresh Token found in the cache. " exception when running BackgroundWorker 

### ISSUE THREAD

**Issue by mywhere** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
Running SPA and API, logged in with some valid users and call Web API. 
After that, able to see the correct records in SQL Azure for MsalAccountActivities and TestCache, which share the same Id and CacheKey. 
But when trying to run BackgroundWorker, it raised exception saying "No Refresh Token found in the cache. "
More detail callstack:

at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<FindRefreshTokenOrFailAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<RefreshRtOrFailAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<ExecuteAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<ExecuteAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.<ExecuteAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.<ExecuteAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at BackgroundWorker.Program.<RunAsync>d__4.MoveNext() in C:\git\ms-identity-dotnet-advanced-token-cache\1-Integrated-Cache\1-2-WebAPI-BgWorker\BackgroundWorker\Program.cs:line 122
 

### Any log messages given by the failure
>
at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<FindRefreshTokenOrFailAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<RefreshRtOrFailAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<ExecuteAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.<ExecuteAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.<ExecuteAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.<ExecuteAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at BackgroundWorker.Program.<RunAsync>d__4.MoveNext() in C:\git\ms-identity-dotnet-advanced-token-cache\1-Integrated-Cache\1-2-WebAPI-BgWorker\BackgroundWorker\Program.cs:line 122

### Expected/desired behavior
>
BackgroundWorker should able to retrieve the accessToken correctly with cached refresh token.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by finbarw** [comment]
I'm also having the same issue, albeit with the sample implemented into my code. Would be great to get some help with it!

**Comment by TanmayDharmaraj** [comment]
Following this sample, I was able to successfully write the token to the cache. But using the token in the `BackgroundWorker` fails with an error `No refresh token found in cache`.

I stumbled upon [this](https://www.cloudidentity.com/blog/2015/08/13/adal-3-didnt-return-refresh-tokens-for-5-months-and-nobody-noticed/) which mentions that refresh tokens are no longer being sent. I did confirm this by deserializing the token and found that refresh token in indeed missing from the SQL database as well.  Below is the json value in `dbo.TokenCache` (redacted values)

Any help to get this working would really be appreciated. I will report back here as well if I end up finding a solution to get this sample working

#### dbo.TokenCache
```json
{
    "AccessToken": {
        "<user-id>.<tenant-id>-login.windows.net-accesstoken-<client-id-webapi-sharedtokencache>-<tenant-id>-user.read profile openid email": {
            "home_account_id": "<user-id>.<tenant-id>",
            "environment": "login.windows.net",
            "client_info": "<client-info>",
            "client_id": "<client-id-webapi-sharedtokencache>",
            "secret": "<access-token>",
            "credential_type": "AccessToken",
            "realm": "<tenant-id>",
            "target": "User.Read profile openid email",
            "user_assertion_hash": "dsM_VR5FvPs95bkNgzWhvHYsoLRZiLKLuHRph8REwv8",
            "cached_at": "1653367319",
            "expires_on": "1653372423",
            "extended_expires_on": "1653372423",
            "ext_expires_on": "1653372423"
        }
    },
    "RefreshToken": {}, //no refresh token
    "IdToken": {
        "<user-id>.<tenant-id>-login.windows.net-idtoken-<client-id-webapi-sharedtokencache>-<tenant-id>-": {
            "home_account_id": "<user-id>.<tenant-id>",
            "environment": "login.windows.net",
            "client_info": "<client-info>",
            "client_id": "<client-id-webapi-sharedtokencache>",
            "secret": "<id-token-value>",
            "credential_type": "IdToken",
            "realm": "<tenant-id>"
        }
    },
    "Account": {
        "<user-id>.<tenant-id>-login.windows.net-<tenant-id>": {
            "home_account_id": "<user-id>.<tenant-id>",
            "environment": "login.windows.net",
            "client_info": "<client-info>",
            "username": "<upn>",
            "name": "<user-name>",
            "local_account_id": "<user-id>",
            "authority_type": "MSSTS",
            "realm": "<tenant-id>"
        }
    },
    "AppMetadata": {
        "appmetadata-login.windows.net-<client-id-webapi-sharedtokencache>": {
            "environment": "login.windows.net",
            "client_id": "<client-id-webapi-sharedtokencache>"
        }
    }
}
```

**Comment by v-michaelmi** [comment]
@mywhere is your application configured to use **SQL** or **Redis**?

**Comment by v-michaelmi** [comment]
@mywhere @TanmayDharmaraj 

Would you guys be able to share the `DefaultSlidingExpiration` setting for your background workers?

If this value is not set it will default to 20 minutes

![image](https://user-images.githubusercontent.com/93682173/176316685-10a8aa20-7d2e-4584-a7bb-21a5ae69c7f0.png)

**Comment by v-michaelmi** [comment]
Checking in.

Did the above help diagnose or resolve your issue?

**Comment by cmgilles** [comment]
Also running into this issue, if anyone can point me in the right direction, it would be much appreciated! 

Sliding windows in webapp and background worker are both 2 hours (didn't touch them in the code)

Here is what I am doing:

1. clear both tables in sql database
2. login via webapp (it asks to keep me signed in, so my understanding is that means offline_access scope has been requested)
3. call web api
4. verify there is one row in each sql table
5. wait 30 seconds
6. start the background worker
7. fails with error of no refresh token in the cache

**Comment by v-michaelmi** [comment]
Reran the sample and found a bug within the `BackgroundWorkerTokenCacheAdapter` class.

There is a pull request [here](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/pull/17).

@cmgilles if you need the sample to work adding the following methods in the `BackgroundWorkerTokenCacheAdapter.cs` file should resolve your issues.

```
        protected override async Task RemoveKeyAsync(string cacheKey, CacheSerializerHints cacheSerializerHints)
        {
            _logger.LogInformation($"RemoveKeyAsync::cacheKey-'{cacheKey}'");
            await _distributedCache.RemoveAsync(_cacheKey).ConfigureAwait(false);
        }

        protected override async Task<byte[]> ReadCacheBytesAsync(string cacheKey, CacheSerializerHints cacheSerializerHints)
        {
            _logger.LogDebug($"ReadCacheBytesAsync::cacheKey-'{cacheKey}'");
            return await _distributedCache.GetAsync(_cacheKey).ConfigureAwait(false);
        }

        protected override async Task WriteCacheBytesAsync(string cacheKey, byte[] bytes, CacheSerializerHints cacheSerializerHints)
        {
            _logger.LogInformation($"WriteCacheBytesAsync::cacheKey-'{cacheKey}'");
            await _distributedCache.SetAsync(_cacheKey, bytes, _cacheOptions).ConfigureAwait(false);
        }
``` 

Be sure to add `using Microsoft.Identity.Web.TokenCacheProviders.Distributed;` at the top of the file to include the **CacheSerializerHints**.

From a high level, the issues seems to be how the tokens are stored in SQL. In sample `1-1` the default identifiers are used for each token which the `Microsoft.Identity.Client` uses to query for tokens. In sample `1-2`, however, the tokens are serialized with a different ID which is why the adapter is used to ensure the core library is querying for the correct tokens. The original code only overrode one of the `Remove`, `Read` and `Write` methods that did not accept `CacheSerializerHints` as a parameter which resulted in cache misses.

Let me know if this resolves your issues.

**Comment by cmgilles** [comment]
> Reran the sample and found a bug within the `BackgroundWorkerTokenCacheAdapter` class.
> 
> There is a pull request [here](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/pull/17).
> 
> @cmgilles if you need the sample to work adding the following methods in the `BackgroundWorkerTokenCacheAdapter.cs` file should resolve your issues.
> 
> ```
>         protected override async Task RemoveKeyAsync(string cacheKey, CacheSerializerHints cacheSerializerHints)
>         {
>             _logger.LogInformation($"RemoveKeyAsync::cacheKey-'{cacheKey}'");
>             await _distributedCache.RemoveAsync(_cacheKey).ConfigureAwait(false);
>         }
> 
>         protected override async Task<byte[]> ReadCacheBytesAsync(string cacheKey, CacheSerializerHints cacheSerializerHints)
>         {
>             _logger.LogDebug($"ReadCacheBytesAsync::cacheKey-'{cacheKey}'");
>             return await _distributedCache.GetAsync(_cacheKey).ConfigureAwait(false);
>         }
> 
>         protected override async Task WriteCacheBytesAsync(string cacheKey, byte[] bytes, CacheSerializerHints cacheSerializerHints)
>         {
>             _logger.LogInformation($"WriteCacheBytesAsync::cacheKey-'{cacheKey}'");
>             await _distributedCache.SetAsync(_cacheKey, bytes, _cacheOptions).ConfigureAwait(false);
>         }
> ```
> 
> Be sure to add `using Microsoft.Identity.Web.TokenCacheProviders.Distributed;` at the top of the file to include the **CacheSerializerHints**.
> 
> From a high level, the issues seems to be how the tokens are stored in SQL. In sample `1-1` the default identifiers are used for each token which the `Microsoft.Identity.Client` uses to query for tokens. In sample `1-2`, however, the tokens are serialized with a different ID which is why the adapter is used to ensure the core library is querying for the correct tokens. The original code only overrode one of the `Remove`, `Read` and `Write` methods that did not accept `CacheSerializerHints` as a parameter which resulted in cache misses.
> 
> Let me know if this resolves your issues.

Worked.  Thanks!

**Comment by v-michaelmi** [comment]
Fix complete with [commit c34902](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/pull/17/commits/c3490270d9c22db181ff45b44d3dbb8d43a22eed).

Please feel free to re-open if issue persists.

**Comment by luismanez** [comment]
This is still not working for me. It **does** work when using MS Identity Web library 1.14 (the version used by this sample), but is **NOT** working when upgrading to MS Identity web latest version 1.25.1. When upgrading this library, I also needed to update these other libraries to avoid downgrading issues:

```
    <PackageReference Include="Microsoft.Identity.Client" Version="4.42.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.25.1" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.25.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
```

I'm using Redis cache, and when I call the API, a new entry is added to Redis. When I see the item, I have an Access token, but not a refresh token:

![image](https://user-images.githubusercontent.com/9392197/185154659-8cb6c9ed-0289-4e6e-8d36-9fb445737c84.png)

Also, this seems more like a generic issue either in MS Identity Web, or MSAL. Thing is that I have a Web API in production, working for a long time, and I now realised the Refresh token is not being cached either. My Web API is configured following this cache approach: https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization (again, using Redis cache). In the past, I´m sure the Refresh token was cached (likely cos I was using a lower version).

Please @v-michaelmi could you try with latest MS Identity web?

Many thanks.

**Comment by v-michaelmi** [comment]
@luismanez 

Thank you for your patience.

These issues have been resolved with the merge of [pull request 18](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/pull/18)

You should now be able to run this sample using the latest libraries without issue.

You mention a viable solution already [here](https://github.com/AzureAD/microsoft-identity-web/issues/1846).

For anyone else looking at this issue I'd recommend you look at the issue referenced above and also this documentation on [OBO flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of#long-running-obo-processes).

The changes with the sample now include updated libraries and removal of the **BackgroundWorkerTokenCacheAdapter** class and leverage the [AcquireTokenInLongRunningProcess ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplication.acquiretokeninlongrunningprocess?view=azure-dotnet) method.

```
// BackgroundWorker/Program.cs

var result = await ((ILongRunningWebApi)app)
                .AcquireTokenInLongRunningProcess(
                      scopes,
                      account.AccountCacheKey)
                 .ExecuteAsync();
```

Works for both Redis and SQL.

**Comment by luismanez** [comment]
Thanks @v-michaelmi !! Glad to see the sample update, so it´s still relevant. Worth to mention that if you try this in an Azure Function as background process, you won´t be able to use MS Identity Web library as the Builders, like _MicrosoftIdentityAppCallsWebApiAuthenticationBuilder_, will change Az Function Auth scheme breaking the Function Default Auth mode (Function key, etc). As I mention in the other thread, the solution is to use MSAL with the _AcquireTokenInLongRunningProcess_ (as you show here). Also worth to mention that the MS Identity Web team is working in a new version that will allow to use the library in this scenarios.
Thanks again!
