### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application

### ISSUE THREAD

**Issue by architect-tarun-narang** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Configure the projects as per the instructions provided in the following link :-
https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/tree/master/1-Integrated-Cache/1-2-WebAPI-BgWorker

### Any log messages given by the failure
Open the SPA in the browser and click on Call Web API button --> The below error will be thrown
>
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> MSAL.NetCore.4.17.0.0.MsalUiRequiredException: 
	ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID '0b76e815-fcb7-45bf-87ab-8201461ad821' named 'WebApi-SharedTokenCache'. Send an interactive authorization request for this user and resource.
Trace ID: 954ee60b-7dc1-4423-a41c-9c850aa65600
Correlation ID: ce5777e0-bfb1-41de-80b8-833aeb03b29b
Timestamp: 2021-04-24 10:40:10Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.OnBehalfOfRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenOnBehalfOfParameters onBehalfOfParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant, String userFlow, ClaimsPrincipal user)
   at WebAPI.TokenAcquisitionCredentialProvider.AuthenticateRequestAsync(HttpRequestMessage request) in C:\ProjectsSample\Azure-Samples\backgroundjobs\ms-identity-dotnet-advanced-token-cache-master\1-Integrated-Cache\1-2-WebAPI-BgWorker\WebAPI\TokenAcquisitionCredentialProvider.cs:line 26
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
	StatusCode: 400 
	ResponseBody: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '0b76e815-fcb7-45bf-87ab-8201461ad821' named 'WebApi-SharedTokenCache'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 954ee60b-7dc1-4423-a41c-9c850aa65600\r\nCorrelation ID: ce5777e0-bfb1-41de-80b8-833aeb03b29b\r\nTimestamp: 2021-04-24 10:40:10Z","error_codes":[65001],"timestamp":"2021-04-24 10:40:10Z","trace_id":"954ee60b-7dc1-4423-a41c-9c850aa65600","correlation_id":"ce5777e0-bfb1-41de-80b8-833aeb03b29b","suberror":"consent_required"} 
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: ce5777e0-bfb1-41de-80b8-833aeb03b29b
x-ms-request-id: 954ee60b-7dc1-4423-a41c-9c850aa65600
x-ms-ests-server: 2.1.11654.16 - KRSLR1 ProdSlices
x-ms-clitelem: 1,65001,0,,
Set-Cookie: fpc=AvQQFFYtnTxOjNcl4l34wvDKWx4SAQAAAInsFdgOAAAA; expires=Mon, 24-May-2021 10:40:10 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Sat, 24 Apr 2021 10:40:09 GMT

   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UserRequest.GetAsync(CancellationToken cancellationToken)
   at WebAPI.Controllers.ProfileController.Get() in C:\ProjectsSample\Azure-Samples\backgroundjobs\ms-identity-dotnet-advanced-token-cache-master\1-Integrated-Cache\1-2-WebAPI-BgWorker\WebAPI\Controllers\ProfileController.cs:line 42
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 39846.9345ms 500 text/plain
The thread 0x3918 has exited with code 0 (0x0).
The thread 0x8b3c has exited with code 0 (0x0).

```
### Expected/desired behavior
> 1. On being provided an admin consent in API permissions of WebApi-SharedTokenCache (app registration), the error does not come. However, this scenario should work without the admin consent, that is on behalf of user flow and not with the elevated access. 
2. In addition to this, when the admin consent is provided, the token stored in the database is not the web-app/SPA/user consented token but the web-api token and the same is printed when the background worker console application is executed. However, the expectation is, it should be user consented/SPA token.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@architect-tarun-narang apologies for late response. This is a standard consent issue, the error message says "user or administrator has not consented..." so the user consent would also do, admin consent is not needed. Problem is that the user consent is not provided for some reason. 

1. Can you confirm that you have carried out this [step in particular](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/tree/master/1-Integrated-Cache/1-2-WebAPI-BgWorker#configure-known-client-applications-for-service-webapi-sharedtokencache)?

2. Can you confirm you are using the web API scope with the `.default` format i.e. `api://{service_app_client_id}/.default`?

3. Did you register the apps as single-tenant (i.e. **Accounts in this organizational directory only**) or multi-tenant?

**Comment by derisen** [comment]
@architect-tarun-narang regarding this

> In addition to this, when the admin consent is provided, the token stored in the database is not the web-app/SPA/user consented token but the web-api token and the same is printed when the background worker console application is executed. However, the expectation is, it should be user consented/SPA token.

Can you clarify what you mean by web-api token? is that the token meant for web api? what is the scope and audience? You can share the claims in an expired token here.

**Comment by architect-tarun-narang** [comment]
1. Can you confirm that you have carried out this step in particular?
Yes, It was done. Here is the manifest file of WebApi-SharedTokenCache

`{
	"id": "f491d4a0-6054-47ba-be6a-2666a051d6c3",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "0b76e815-fcb7-45bf-87ab-8201461ad821",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2021-04-23T13:19:07Z",
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://0b76e815-fcb7-45bf-87ab-8201461ad821"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [
		"21dba92c-678b-4af7-854f-c88c3b38f65f"`

2. Can you confirm you are using the web API scope with the .default format i.e. api://{service_app_client_id}/.default?
I hope you meant here to set the API scope in SPA application. In authConfig.js file of SPA, the scope is set as default, below is the content of the file

`
export const msalConfig = {
    auth: {
        clientId: "21dba92c-678b-4af7-854f-c88c3b38f65f",
        authority: "https://login.microsoftonline.com/4a95f16f-35ba-4a52-9cb3-7f300cdc0c60",
        redirectUri: "http://localhost:22724",
    },
    cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false // Set this to "true" if you are having issues on IE11 or Edge
    },
}


export const webApiConfig = {
    apiURI: "https://localhost:44351/api/profile",
    resourceScope: "api://0b76e815-fcb7-45bf-87ab-8201461ad821/.default"
}

/** 
 * Scopes you enter here will be consented once you authenticate. For a full list of available authentication parameters, 
 * visit https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/modules/_authenticationparameters_.html
 */
export const loginRequest = {
    scopes: ["openid", "profile", webApiConfig.resourceScope]
}

// Add here scopes for access token to be used at the API endpoint.
export const tokenRequest = {
    scopes: [webApiConfig.resourceScope, "offline_access"]
}
`
3. Did you register the apps as single-tenant (i.e. Accounts in this organizational directory only) or multi-tenant?
It's single tenant.

**Comment by derisen** [comment]
@architect-tarun-narang strange, there are no scopes here that would require admin consent. Just to check, what does the consent screen look like when you first sign-in to the app? One thing you can do is to [delete service principals](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnet-webapi-multitenant/tree/master/Chapter1#how-to-delete-service-principals), recreate them and sign-in again to see the consent screen again.

Regardless, it would be best to inspect a network trace here. Can you capture the trace using something like [Fiddler](https://www.telerik.com/fiddler), and send it to me over email? My email is on my GitHub profile.

**Comment by derisen** [comment]
Closing due to inactivity. Let us know.
